### ISSUE TITLE
Create Basic authentication for WSDL URL

### ISSUE THREAD

**Issue by henriqueso** [camiloarthur/WsdlFlattener#1]

**Comment by fischerp** [comment]
Thanks henriqueso for your suggestion! It's implemented
wf [WSDL LOCATION] [OUTPUT FILE](no authentication required)
wf [WSDL LOCATION] [OUTPUT FILE] [USERNAME] [PASSWORD]  
wf [WSDL LOCATION] [OUTPUT FILE] [USERNAME] [PASSWORD] [DOMAIN]
